title: Salah's Blog
description: A place where I share my thoughts and expertise


# Build settings
markdown: kramdown

# URL settings
baseurl: "" # Important for correct pathing with jekyll-polyglot relative_url
url: "https://Salah-Sal.github.io"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives

# Collections - Separate English and Arabic
collections:
  posts_en:
    output: true
    permalink: /en/blog/:year/:month/:day/:title/
  posts_ar:
    output: true
    permalink: /ar/blog/:year/:month/:day/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts_en"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: ""
      type: "posts_ar"
    values:
      layout: "post" 
      lang: "ar"
  - scope:
      path: "blog"
    values:
      layout: "default"
  - scope:
      path: "about"
    values:
      layout: "default"

# Giscus Comments Configuration
giscus:
  repo: "Salah-Sal/Salah-Sal.github.io"
  repo_id: "R_kgDONN7Cmw"
  category: "General"
  category_id: "DIC_kwDONN7Cm84Cqekk"
  mapping: "pathname" # e.g., "pathname", "url", "title", "og:title"
  strict: "0" # Or 0
  reactions_enabled: "1" # Or 1
  emit_metadata: "0" # Or 0
  input_position: "bottom" # "top" or "bottom"
  theme: "preferred_color_scheme" # This will automatically adapt to the user's system theme
  # lang will be handled dynamically in the script include


# Jekyll Archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category_archive
  permalinks:
    category: '/blog/category/:name/'