title: Salah's Blog
description: A place where I share my thoughts and expertise


# Build settings
markdown: kramdown

# URL settings
baseurl: "" # Important for correct pathing with jekyll-polyglot relative_url
url: "https://Salah-Sal.github.io"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives

# Collections - Separate English and Arabic
collections:
  posts_en:
    output: true
    permalink: /en/blog/:year/:month/:day/:title/
  posts_ar:
    output: true
    permalink: /ar/blog/:year/:month/:day/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts_en"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: ""
      type: "posts_ar"
    values:
      layout: "post" 
      lang: "ar"
  - scope:
      path: "blog"
    values:
      layout: "default"
  - scope:
      path: "about"
    values:
      layout: "default"

# Giscus Comments Configuration
giscus:
  repo: "Salah-Sal/Salah-Sal.github.io"
  repo_id: "R_kgDONN7Cmw"
  category: "General"
  category_id: "DIC_kwDONN7Cm84Cqekk"
  mapping: "pathname" # e.g., "pathname", "url", "title", "og:title"
  strict: "0" # Or 0
  reactions_enabled: "1" # Or 1
  emit_metadata: "0" # Or 0
  input_position: "bottom" # "top" or "bottom"
  theme: "preferred_color_scheme" # This will automatically adapt to the user's system theme
  # lang will be handled dynamically in the script include

# Pagination Settings (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 5 # Number of posts per page
  permalink: '/page/:num/' # For the default language (English) blog listing
  # The collection 'posts' will be paginated.
  # Polyglot specific settings for collections:
  # We need to tell Polyglot to handle the main posts collection.
  # This is usually done by ensuring posts have 'lang' frontmatter,
  # which we did in Sprint 3. Polyglot then creates language-specific versions.
  # For jekyll-paginate-v2 with Polyglot, the paths for non-default languages
  # are typically handled by Polyglot's URL rewriting.
  # We will paginate the main blog page (blog/index.html).
  # jekyll-paginate-v2 should pick up the posts for the current language
  # if Polyglot correctly filters site.posts before pagination runs for a given page.

  # We'll keep it simple first and see if Polyglot handles it.
  # If not, more specific collection pagination config might be needed.
  # Title for paginated pages (optional, for SEO):
  title: ':title - page :num'

# Jekyll Archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category_archive
  permalinks:
    category: '/blog/category/:name/'