title: Your Professional Blog
description: A place where I share my thoughts and expertise
theme: minima

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Base URL settings
baseurl: ""
url: ""

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"